### ISSUE TITLE
Vs 2019 support

### ISSUE THREAD

**Issue by timker** [szehetner/BenchmarkDotNet-VS-Runner#2]
would be great to have VS 2019  support, now that it's out

**Comment by szehetner** [comment]
I just published a new version for VS 2019 (0.9.0).

**Comment by timker** [comment]
Thanks, It's now installable in 2019

**Comment by JonathanHiggs** [comment]
On marketplace it looks like there is now only VS2019 support. Could you update to support 2017 + 2019?

**Comment by szehetner** [comment]
The latest version supports only VS 2019 on purpose. I know from experience with Inlining Analyzer that it's quite a lot of effort to support both 2017 and 2019 in the same package and a pain to maintain this, so I didn't want to do it for the Benchmark Runner.

You can however manually download and install the last version that supported VS 2017 from [here](https://github.com/szehetner/BenchmarkDotNet-VS-Runner/releases/tag/0.8.1). This version only lacks minor improvements in comparison to the VS 2019 version (see [the release notes](https://github.com/szehetner/BenchmarkDotNet-VS-Runner/blob/master/ReleaseHistory.md) for details.
